name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '10 * * * *'

jobs:
  baustellen:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Check out this repo
      if: always()
      uses: actions/checkout@v3
    - name: baustellen
      if: always()
      run: |-
        curl 'https://stoerungen.apps.swm.de/api/versorgungsunterbrechungen?status=IN_BEARBEITUNG&status=GEPLANT&status=ERLEDIGT' \
          -H 'authority: stoerungen.apps.swm.de' \
          -H 'accept: text/html,application/xhtml+xml,application/json;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
          -H 'cache-control: no-cache' \
          -H 'pragma: no-cache' \
          -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0' \
          --compressed > baustellen.json
    - name: Commit and push if it changed
      if: always()
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
  
